# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui2.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(538, 508)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_name = QtWidgets.QLabel(self.centralwidget)
        self.label_name.setGeometry(QtCore.QRect(230, 10, 71, 21))
        self.label_name.setObjectName("label_name")
        self.label_name2 = QtWidgets.QLabel(self.centralwidget)
        self.label_name2.setGeometry(QtCore.QRect(150, 80, 20, 20))
        self.label_name2.setObjectName("label_name2")
        self.input_name = QtWidgets.QLineEdit(self.centralwidget)
        self.input_name.setGeometry(QtCore.QRect(180, 80, 113, 21))
        self.input_name.setObjectName("input_name")
        self.label_name3 = QtWidgets.QLabel(self.centralwidget)
        self.label_name3.setGeometry(QtCore.QRect(230, 130, 71, 16))
        self.label_name3.setObjectName("label_name3")
        self.radio_button = QtWidgets.QRadioButton(self.centralwidget)
        self.radio_button.setGeometry(QtCore.QRect(210, 170, 100, 20))
        self.radio_button.setObjectName("radio_button")
        self.radio_button2 = QtWidgets.QRadioButton(self.centralwidget)
        self.radio_button2.setGeometry(QtCore.QRect(210, 210, 100, 20))
        self.radio_button2.setObjectName("radio_button2")
        self.button_name = QtWidgets.QPushButton(self.centralwidget)
        self.button_name.setGeometry(QtCore.QRect(200, 280, 113, 32))
        self.button_name.setObjectName("button_name")
        self.label_name5 = QtWidgets.QLabel(self.centralwidget)
        self.label_name5.setGeometry(QtCore.QRect(120, 380, 51, 20))
        self.label_name5.setObjectName("label_name5")
        self.label_name4 = QtWidgets.QLabel(self.centralwidget)
        self.label_name4.setGeometry(QtCore.QRect(120, 330, 51, 20))
        self.label_name4.setObjectName("label_name4")
        self.input_name2 = QtWidgets.QLineEdit(self.centralwidget)
        self.input_name2.setGeometry(QtCore.QRect(180, 330, 181, 21))
        self.input_name2.setObjectName("input_name2")
        self.label_name6 = QtWidgets.QLabel(self.centralwidget)
        self.label_name6.setGeometry(QtCore.QRect(180, 380, 181, 16))
        self.label_name6.setStyleSheet("j")
        self.label_name6.setText("")
        self.label_name6.setObjectName("label_name6")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 538, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Project 2"))
        self.label_name.setText(_translate("MainWindow", "Voting App"))
        self.label_name2.setText(_translate("MainWindow", "ID:"))
        self.label_name3.setText(_translate("MainWindow", "Candidates"))
        self.radio_button.setText(_translate("MainWindow", "Jane"))
        self.radio_button2.setText(_translate("MainWindow", "John"))
        self.button_name.setText(_translate("MainWindow", "SUBMIT"))
        self.label_name5.setText(_translate("MainWindow", "Status:"))
        self.label_name4.setText(_translate("MainWindow", "Results:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
